# backend/scripts/generate_accuracy_sweep.py
"""
Generates data/precomputed/accuracy_vs_budget.json.

Run from backend/:
    python scripts/generate_accuracy_sweep.py

This is REAL data produced by the CacheQuake toy simulator using the
lightly-trained model (model_weights/toy_transformer.pt).
The model is NOT a pretrained LLM -- it is a small Transformer trained
for ~3,000 steps on the same synthetic task used in the demo.
Do NOT compare these numbers to published LLM benchmarks.

LOCK NOTE: Once the frontend starts citing numbers from this file,
re-generation must be flagged to the team lead first.
"""

import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import json, time
import torch

from app.model.toy_transformer import ToyTransformer
from app.model.vocab import VOCAB_SIZE
from app.cache_policies.full_cache import FullCachePolicy
from app.cache_policies.sliding_window import SlidingWindowPolicy
from app.cache_policies.heavy_hitter import HeavyHitterPolicy
from app.cache_policies.bdh_inspired_state import BDHInspiredState
from app.tasks.needle_haystack import NeedleHaystackTask
from app.simulation.runner import run_episode

# ---- Paths ------------------------------------------------------------------
WEIGHTS_DIR   = os.path.normpath(
    os.path.join(os.path.dirname(__file__), "..", "model_weights"))
CKPT_PATH     = os.path.join(WEIGHTS_DIR, "toy_transformer.pt")
META_PATH     = os.path.join(WEIGHTS_DIR, "training_metadata.json")
OUT_PATH      = os.path.normpath(
    os.path.join(os.path.dirname(__file__), "..", "data", "precomputed",
                 "accuracy_vs_budget.json"))

# ---- Config -----------------------------------------------------------------
N_EPISODES      = 80          # episodes per (policy, budget) — more = less noisy
N_FACTS         = 3
SEQ_LEN         = 120
QUESTION_TARGET = 0
BUDGETS         = [4, 8, 16, 32, 64, 96]
STATE_SIZES     = [4, 8, 16, 32, 64, 96]
D_HEAD          = 16
N_HEADS         = 4

# ---- Load model -------------------------------------------------------------
model = ToyTransformer(vocab_size=VOCAB_SIZE, d_model=64, n_heads=N_HEADS,
                       n_layers=4, max_seq_len=512)

if os.path.exists(CKPT_PATH):
    model.load_state_dict(
        torch.load(CKPT_PATH, map_location="cpu", weights_only=True))
    model_state = "lightly_trained"
    training_meta = json.load(open(META_PATH)) if os.path.exists(META_PATH) else {}
    print(f"Loaded trained weights from {CKPT_PATH}")
else:
    model_state   = "randomly_initialized"
    training_meta = {}
    print("WARNING: No checkpoint found -- using random weights. Curves will be noise.")

model.eval()


def run_accuracy(policy_fn, n_episodes: int, base_seed: int = 100) -> float:
    """Run n_episodes and return first-character match accuracy."""
    # Use base_seed=100 (different from training seed=42) to avoid
    # accidentally measuring memorized training examples.
    correct = 0
    for i in range(n_episodes):
        task    = NeedleHaystackTask(seed=base_seed + i)
        episode = task.generate(n_facts=N_FACTS, seq_len=SEQ_LEN,
                                question_target=QUESTION_TARGET)
        policy  = policy_fn()
        result  = run_episode(model, policy, episode, "sweep", {})
        if result.correct:
            correct += 1
    return round(correct / n_episodes, 4)


t_start = time.time()

results = {
    "LOCK_STATUS": "LOCKED",
    "LOCK_NOTE": (
        "This file is the final version shipped with the CacheQuake submission. "
        "Do not silently re-generate after the frontend or one-pager starts "
        "citing these numbers -- flag to team lead first."
    ),
    "IMPORTANT": (
        "Data generated by the CacheQuake toy simulator using a lightly-trained "
        "model (NOT a pretrained LLM, NOT a benchmark model). "
        "The model was trained for 3,000 steps on synthetic needle-haystack "
        "episodes -- enough for the curves to show meaningful cache-policy signal, "
        "not enough to compare with published LLM results. "
        "See model_state and training fields for exact details."
    ),
    "data_status":  "precomputed_by_us",
    "model_state":  model_state,
    "training":     training_meta.get("training", {"note": "no metadata found"}),
    "sweep_config": {
        "n_episodes":      N_EPISODES,
        "n_facts":         N_FACTS,
        "seq_len":         SEQ_LEN,
        "question_target": QUESTION_TARGET,
        "eval_seed_base":  100,
        "note": (
            "Evaluation seeds start at 100 (training used seed 42) to avoid "
            "measuring memorized training episodes."
        ),
    },
    "policies": {}
}

# ---- full_cache (control, budget = unbounded) --------------------------------
print("Running full_cache ...")
acc = run_accuracy(lambda: FullCachePolicy(), N_EPISODES)
results["policies"]["full_cache"] = {
    "data_status":  "precomputed_by_us",
    "description":  "Keeps all tokens (unbounded budget). Control condition.",
    "data": [{"budget": "inf", "accuracy": acc}],
}
print(f"  full_cache: {acc}")

# ---- sliding_window ----------------------------------------------------------
print("Running sliding_window ...")
sw_data = []
for budget in BUDGETS:
    acc = run_accuracy(
        lambda b=budget: SlidingWindowPolicy(window_size=b, num_sink_tokens=0),
        N_EPISODES)
    sw_data.append({"budget": budget, "accuracy": acc, "data_status": "precomputed_by_us"})
    print(f"  sliding_window budget={budget}: {acc}")
results["policies"]["sliding_window"] = {
    "data_status":  "precomputed_by_us",
    "description":  "Keeps most recent `budget` tokens. num_sink_tokens=0 (naive).",
    "data":         sw_data,
}

# ---- heavy_hitter ------------------------------------------------------------
print("Running heavy_hitter ...")
hh_data = []
for budget in BUDGETS:
    acc = run_accuracy(
        lambda b=budget: HeavyHitterPolicy(budget=b),
        N_EPISODES)
    hh_data.append({"budget": budget, "accuracy": acc, "data_status": "precomputed_by_us"})
    print(f"  heavy_hitter budget={budget}: {acc}")
results["policies"]["heavy_hitter"] = {
    "data_status":  "precomputed_by_us",
    "description":  (
        "Keeps `budget` highest-cumulative-score tokens. "
        "H2O-inspired; uses proxy dot-product scores (not softmax weights). "
        "Most-recent token always kept."
    ),
    "data": hh_data,
}

# ---- bdh_inspired_state ------------------------------------------------------
print("Running bdh_inspired_state ...")
bdh_data = []
for state_size in STATE_SIZES:
    acc = run_accuracy(
        lambda s=state_size: BDHInspiredState(
            state_size=s, d_head=D_HEAD, n_heads=N_HEADS, decay=0.9),
        N_EPISODES)
    bdh_data.append({"budget": state_size, "accuracy": acc,
                     "data_status": "precomputed_by_us"})
    print(f"  bdh_inspired_state state_size={state_size}: {acc}")
results["policies"]["bdh_inspired_state"] = {
    "data_status":  "precomputed_by_us",
    "description":  (
        "Toy layer inspired by BDH, not BDH itself. "
        "Fixed state_size slots, soft Hopfield write (decay=0.9). "
        "memory_tokens_used() == state_size always (constant)."
    ),
    "data": bdh_data,
}

results["sweep_duration_seconds"] = round(time.time() - t_start, 1)

with open(OUT_PATH, "w") as f:
    json.dump(results, f, indent=2)
print(f"\nWrote {OUT_PATH}")
print(f"Total sweep time: {results['sweep_duration_seconds']}s")
